camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All Tasks
    generic-properties:
      properties:
        initializeTelemetry: false

spring.security.user:
  name:     demo
  password: demo

spring.datasource:
  url: jdbc:h2:./camunda-db
  username: sa
  password: sa

